function [ varargout ] = plot_column_lagrangian( time, radius, p_grid, col_id, time_bounce, min_row, max_row, time_shock_chimera, radius_shock, theta_shock )

ncols = size( p_grid, 1 );
theta_init = acos( ( ncols - 2*(1:ncols) + 1 ) / ncols );

ny            = length( theta_shock );

% Define edges of theta grid
theta_edges = linspace( eps, pi, ny+1 );

% Only need inner edges
theta_edges = theta_edges(1:end-1);
        
% Determine to which ray the particles belongs
[~,i_theta_bin] = histc( theta_init, theta_edges );
i_theta = i_theta_bin(col_id);

fig_h = figure;

axis_pos = [ 0.1 0.18 0.85 0.77 ];
yscale   = 'log';
ylim     = [ 1.0001e6 9.9999e8 ];
xlim     = [ 0.00001 1.39999];

axis_h(1) = axes( 'Parent', fig_h, ...
    'Position', axis_pos, ...
    'NextPlot', 'add', ...
    'XMinorTick', 'on', ...
    'Box', 'on', ...
    'FontSize', 18, ...
    'TickLabelInterpreter_I', 'latex', ...
    'Yscale', yscale, ...
    'YLim', ylim, ...
    'XLim', xlim );

group_h(1) = hggroup( 'Parent', axis_h(1), 'DisplayName', sprintf( 'C%d', col_id ) );
set(get(get(group_h(1),'Annotation'),'LegendInformation'),'IconDisplayStyle','on');

LineWidth = 0.5;
LineSet = { '-'; '--'; '-.'; ':' };

p_rows = min_row:max_row;
p_col  = p_grid( col_id, p_rows );

nrows = length(p_rows);

for id = 1:nrows
    row_id = p_rows(id);
    line_h(row_id) = plot( time - time_bounce, radius(:,p_col(id)), ...
        'DisplayName', sprintf( 'P%d', p_grid( col_id, row_id ) ), ...
        'Color', 'k', ...
        'LineStyle', LineSet{1,:}, ...
        'LineWidth', LineWidth, ...
        'Marker', 'none', ...
        'Parent', group_h(1) );
end

plot( time_shock_chimera - time_bounce, radius_shock(:,i_theta), ...
    'DisplayName', '$R_\mathrm{shock}(\theta)$', ...
    'Color', 'm', ...
    'LineStyle', '-', ...
    'LineWidth', 2.0, ...
    'Marker', 'none', ...
    'Parent', axis_h(1) );

plot( time_shock_chimera - time_bounce, mean( radius_shock, 2 ), ...
    'DisplayName', '$\langle R_{\mathrm{shock}} \rangle$', ...
    'Color', 'm', ...
    'LineStyle', '--', ...
    'LineWidth', 2.0, ...
    'Marker', 'none', ...
    'Parent', axis_h(1) );

leg_h = legend( axis_h(1), 'Location', 'East' );
set( leg_h, 'Interpreter', 'latex', 'Color', 'none', 'EdgeColor', 'none', 'FontSize', 18 );

end