function nnse_mass = import_nnse_mass(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   EJECTA_MASS = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default selection.
%
%   EJECTA_MASS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   ejecta_mass = importfile('trace_ejecta_mass.dat', 5, 1478);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/05/21 11:12:07

%% Initialize variables.
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format string for each line of text:
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
%	column17: double (%f)
%   column18: double (%f)
%	column19: double (%f)
%   column20: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*39s%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%17f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try
% regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works
% for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
nnse_mass = [dataArray{1:end-1}];
nnse_mass = nnse_mass(:,[15,16,1:12,17,13:14]);
